- hosts: webservers
  tasks:

  - name: "Get Git Repo"
    git:
      repo: git@github.com:ThomasHayen1308/P4ForceIT-Back.git
      dest: /var/www/spring/P4ForceIT-Back
      force: yes

  - name: "Change execution rights Maven Wrapper"
    file: dest=/var/www/spring/P4ForceIT-Back/mvnw mode=a+x
    
  - name: "Run Maven Wrapper"
    shell: "cd /var/www/spring/P4ForceIT-Back && nohup ./mvnw spring-boot:run &"
    ignore_errors: true
