- hosts: webservers
  tasks:

  - name: "Get Git Repo"
    git:
      repo: git@github.com:ThomasHayen1308/P4ForceIT-Back.git
      dest: /var/www/spring/P4ForceIT-Back
      force: yes

  - name: "Change execution rights Maven Wrapper"
    command: chmod +x mvnw
    args:
      chdir: /var/www/spring/P4ForceIT-Back

