- hosts: webservers
  become: yes
  tasks:

  - name: Get Git Repo
    git:
      repo: git@github.com:ThomasHayen1308/P4ForceIT-Front.git
      dest: /var/www/html/
    sudo_user: ubuntu

  - name: "Started nginx"
    service:
      name: nginx
      state: started

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
