- hosts: webservers
  become: yes
  tasks:

  - name: "Get Git Repo"
    git:
      repo: https://github.com/ThomasHayen1308/P4ForceIT-Front
      dest: /var/www/html/P4ForceIT-Front

  - name: Change directory to Project folder
    command: arg1
    args:
      chdir: /var/www/html/P4ForceIT-Front
   
  - name: Run Angular build
    command: ng build

  - name: "Started nginx"
    service:
      name: nginx
      state: started

  - name: "Restart nginx"
    service:
      name: nginx
      state: restarted
