- hosts: webservers
  become: yes
  tasks:

  - name: Pull github repo
    git:
      repo: https://github.com/ThomasHayen1308/P4ForceIT-Front
      dest: /var/www/html/P4ForceIT-Front
      update: yes
      version: master

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
