- hosts: webservers
  become: yes
  tasks:

  - name: "Get Git Repo"
    git:
      repo: https://github.com/ThomasHayen1308/P4ForceIT-Front
      dest: /var/www/html/P4ForceIT-Front

  - name: Build Angular Project
    command: ng build --prod --no-build-optimizer
    args:
      chdir: "/var/www/html/P4ForceIT-Front"

  - name: "Started nginx"
    service:
      name: nginx
      state: started

  - name: "Restart nginx"
    service:
      name: nginx
      state: restarted
